=== vickymx/University/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dictionary (word+)>
<!ELEMENT word (lemma, morph, syn)>
<!ELEMENT lemma (#PCDATA)>
<!ATTLIST lemma 
    pos (V|N|A|Adv|Pron) #REQUIRED
    aspect (св.|несв.|двувидов) #REQUIRED
    conj (1|2|3|изкл.) #REQUIRED   
    def (безличен|третоличен|множественолични) #IMPLIED
    refl (се|си) #IMPLIED
>
<!ELEMENT morph (personal_forms, participles, gerund?, imperative?)>
<!ELEMENT personal_forms (form+)>
<!ELEMENT form (#PCDATA)>
<!ATTLIST form
    tense (сегашно|аорист|имперфект) #REQUIRED
    person (1|2|3) #REQUIRED
    number (ед.|мн.) #REQUIRED
>

<!ELEMENT participles (participle+)>
<!ELEMENT participle (#PCDATA)>
<!ATTLIST participle
   type (мин.св.д.|мин.несв.д.|стр.|сег.д.) #REQUIRED
   number (ед.|мн.) #REQUIRED
   gender (м.|ж.|ср.) #IMPLIED
   article (чл.|нечл.) #REQUIRED
>
<!ELEMENT gerund (#PCDATA)>
<!ELEMENT imperative (singular, plural)>
<!ELEMENT singular (#PCDATA)>
<!ELEMENT plural (#PCDATA)>

<!ELEMENT syn (sense+)>
<!ELEMENT sense (def, frame, example, example, example, example, example+)>
<!ELEMENT def (#PCDATA|a)*>
<!ATTLIST def
   src (WN|D|констр.|друго) #REQUIRED
>
<!--WN - WordNet; D - многотомния тълковен речник; конструирана от нас дефиниция; друга-->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a
   ref (агенс|ефектор|екпериенцер|локатив|бенефициент|тема|пациенс) #REQUIRED
>
<!ELEMENT frame (arg?, arg?, arg?)>
<!ELEMENT arg (syntactic_structure, selective_restrictions)>
<!ATTLIST arg
   semantic_role (агенс|ефектор|екпериенцер|локатив|бенефициент|тема|пациенс) #REQUIRED
   function (подлог|пр.доп.|непр.доп.|обст.|ск.опр.) #REQUIRED
>
<!ELEMENT syntactic_structure (NP|AP|AdvP|PP|pro|CP|Pron)+>
<!ELEMENT NP EMPTY>
<!ELEMENT AP EMPTY>
<!ELEMENT AdvP EMPTY>
<!ELEMENT PP EMPTY>
<!ELEMENT pro EMPTY>
<!ELEMENT CP EMPTY>
<!ELEMENT Pron EMPTY>
<!ELEMENT selective_restrictions (sel_restr+)>
<!ELEMENT sel_restr (#PCDATA)>
<!ELEMENT example (#PCDATA|a|p)*>
<!ATTLIST example
    src CDATA #REQUIRED
>
<!ELEMENT p (#PCDATA)>

=== vickymx/University/DictionaryTask.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">
<!--  -->
<dictionary>
  <word>
    <lemma pos="V" aspect="несв." conj="1">играя</lemma>
    <morph>
      <personal_forms>
        <form tense="сегашно" person="1" number="ед.">играя</form>
        <form tense="сегашно" person="2" number="ед.">играеш</form>
        <form tense="сегашно" person="3" number="ед.">играе</form>
      </personal_forms>
      <participles>
          <!-- Причастни форми -->
        <participle type="мин.св.д." number="ед." gender="м." article="нечл.">играл</participle>
        <participle type="мин.св.д." number="ед." gender="ж." article="нечл.">играла</participle>
        <participle type="стр." number="ед." gender="м." article="нечл.">игран</participle>
        <participle type="сег.д." number="ед." gender="м." article="нечл.">играещ</participle>
      </participles>
      <gerund>играейки</gerund>
      <imperative>
        <singular>играй</singular>
        <plural>играйте</plural>
      </imperative>
    </morph>
    <syn>
        <!-- Значение 1 -->
        <sense>
            <def src="D"><a ref="агенс">някой</a> изпълнява роля в <a ref="тема">сценична постановка</a></def>
            <frame>
                <arg semantic_role="агенс" function="подлог">
                    <syntactic_structure><NP/><pro/></syntactic_structure>
                    <selective_restrictions><sel_restr>актьор</sel_restr></selective_restrictions>
                </arg>
            </frame>
            <example src="D"><a ref="агенс">Актьорът</a> <p>играе</p> <a ref="тема">ролята на краля</a>.</example>
            <example src="D"><a ref="агенс">Те</a> <p>играят</p> <a ref="тема">в пиесата</a>.</example>
            <example src="D"><a ref="агенс">Тя</a> <p>играе</p> <a ref="тема">главната роля</a>.</example>
            <example src="D"><a ref="агенс">Групата</a> <p>играе</p> <a ref="тема">в театъра</a>.</example>
            <example src="D"><a ref="агенс">Момичето</a> <p>играе</p> <a ref="тема">Пепеляшка</a>.</example>
            <example src="D"><a ref="агенс">Момчетата</a> <p>играят</p> <a ref="тема">разбойници</a>.</example>
        </sense>
        <!-- Значение 2 -->
        <sense>
            <def src="D"><a ref="агенс">някой</a> участва в <a ref="тема">игра за развлечение</a></def>
            <frame>
                <arg semantic_role="агенс" function="подлог">
                    <syntactic_structure><NP/><pro/></syntactic_structure>
                    <selective_restrictions><sel_restr>дете</sel_restr></selective_restrictions>
                </arg>
            </frame>
            <example src="D"><a ref="агенс">Децата</a> <p>играят</p> <a ref="тема">навън</a>.</example>
            <example src="D"><a ref="агенс">Момчето</a> <p>играе</p> <a ref="тема">с колички</a>.</example>
            <example src="D"><a ref="агенс">Тя</a> <p>играе</p> <a ref="тема">на криеница</a>.</example>
            <example src="D"><a ref="агенс">Кучето</a> <p>играе</p> <a ref="тема">с топка</a>.</example>
            <example src="D"><a ref="агенс">Ние</a> <p>Играем</p> <a ref="тема">настолни игри</a>.</example>
            <example src="D"><a ref="агенс">Групата</a> <p>играе</p> <a ref="тема">на поляната</a>.</example>
        </sense>
        
        <!-- Значение 3 -->
        <sense>
            <def src="D"><a ref="агенс">някой</a> участва в <a ref="тема">спортно състезание</a></def>
            <frame>
                <arg semantic_role="агенс" function="подлог">
                    <syntactic_structure><NP/><pro/></syntactic_structure>
                    <selective_restrictions><sel_restr>спортен участник</sel_restr></selective_restrictions>
                </arg>
            </frame>
            <example src="D"><a ref="агенс">Отборът</a> <p>играе</p> <a ref="тема">футбол</a>.</example>
            <example src="D"><a ref="агенс">Той</a> <p>играе</p> <a ref="тема">тенис</a>.</example>
            <example src="D"><a ref="агенс">Ние</a> <p>играем</p> <a ref="тема">волейбол</a>.</example>
            <example src="D"><a ref="агенс">Тя</a> <p>играе</p> <a ref="тема">на турнира</a>.</example>
            <example src="D"><a ref="агенс">Съзтезателят</a> <p>играе</p> <a ref="тема">финалния мач</a>.</example>
            <example src="D"><a ref="агенс">Младежите</a> <p>играят</p> <a ref="тема">баскетбол</a>.</example>
        </sense>
        
        <!-- Значение 4 -->
        <sense>
            <def src="D"><a ref="агенс">нещо</a> извършва <a ref="тема">метафорично движение</a></def>
            <frame>
                <arg semantic_role="агенс" function="подлог">
                    <syntactic_structure><NP/><pro/></syntactic_structure>
                    <selective_restrictions><sel_restr>естествено явление</sel_restr></selective_restrictions>
                </arg>
            </frame>
            <example src="D"><a ref="агенс">Светлината</a> <p>играе</p> <a ref="тема">върху водата</a>.</example>
            <example src="D"><a ref="агенс">Сянката</a> <p>играе</p> <a ref="тема">по стената</a>.</example>
            <example src="D"><a ref="агенс">Блясъкът</a> <p>играе</p> <a ref="тема">в очите ѝ</a>.</example>
            <example src="D"><a ref="агенс">Пламъкът</a> <p>играе</p> <a ref="тема">в камината</a>.</example>
            <example src="D"><a ref="агенс">Вълните</a> <p>играят</p> <a ref="тема">на брега</a>.</example>
            <example src="D"><a ref="агенс">Звездите</a> <p>играят</p> <a ref="тема">в небето</a>.</example>
        </sense>
        
        <!-- Значение 5 -->
        <sense>
            <def src="D"><a ref="агенс">някой</a> представя <a ref="тема">музика пред публика</a></def>
            <frame>
                <arg semantic_role="агенс" function="подлог">
                    <syntactic_structure><NP/><pro/></syntactic_structure>
                    <selective_restrictions><sel_restr>музикант</sel_restr></selective_restrictions>
                </arg>
            </frame>
            <example src="D"><a ref="агенс">DJ-ят</a> <p>играе</p> <a ref="тема">песен на сцената</a>.</example>
            <example src="D"><a ref="агенс">Тя</a> <p>играе</p> <a ref="тема">хаус музика</a>.</example>
            <example src="D"><a ref="агенс">Музикантът</a> <p>играе</p> <a ref="тема">джаз сет</a>.</example>
            <example src="D"><a ref="агенс">Те</a> <p>играят</p> <a ref="тема">на фестивала</a>.</example>
            <example src="D"><a ref="агенс">Той</a> <p>играе</p> <a ref="тема">техно в клуба</a>.</example>
            <example src="D"><a ref="агенс">Групата</a> <p>играе</p> <a ref="тема">на живо</a>.</example>
        </sense>
        
        <!-- Значение 6 -->
        <sense>
            <def src="D"><a ref="агенс">някой</a> участва във <a ref="тема">видео игра</a></def>
            <frame>
                <arg semantic_role="агенс" function="подлог">
                    <syntactic_structure><NP/><pro/></syntactic_structure>
                    <selective_restrictions><sel_restr>играч</sel_restr></selective_restrictions>
                </arg>
            </frame>
            <example src="D"><a ref="агенс">Те</a> <p>играят</p> <a ref="тема">Minecraft</a>.</example>
            <example src="D"><a ref="агенс">Той</a> <p>играе</p> <a ref="тема">League of Legends</a>.</example>
            <example src="D"><a ref="агенс">Аз</a> <p>играя</p> <a ref="тема">на конзола</a>.</example>
            <example src="D"><a ref="агенс">Тя</a> <p>играе</p> <a ref="тема">симулатор</a>.</example>
            <example src="D"><a ref="агенс">Геймърът</a> <p>играе</p> <a ref="тема">на състезание</a>.</example>
            <example src="D"><a ref="агенс">Ние</a> <p>играем</p> <a ref="тема">онлайн</a>.</example>
        </sense>
        
        <!-- Значение 7 -->
        <sense>
            <def src="D"><a ref="агенс">някой</a> действа според <a ref="тема">чужда роля</a></def>
            <frame>
                <arg semantic_role="агенс" function="подлог">
                    <syntactic_structure><NP/><pro/></syntactic_structure>
                    <selective_restrictions><sel_restr>индивид</sel_restr></selective_restrictions>
                </arg>
            </frame>
            <example src="D"><a ref="агенс">Министърът</a> <p>играе</p> <a ref="тема">по чужда свирка</a>.</example>
            <example src="D"><a ref="агенс">Тя</a> <p>играе</p> <a ref="тема">по сценарий</a>.</example>
            <example src="D"><a ref="агенс">Ръководството</a> <p>играе</p> <a ref="тема">по заповед</a>.</example>
            <example src="D"><a ref="агенс">Той</a> <p>играе</p> <a ref="тема">чужда игра</a>.</example>
            <example src="D"><a ref="агенс">Фирмата</a> <p>играе</p> <a ref="тема">под пазарен натиск</a>.</example>
            <example src="D"><a ref="агенс">Ние</a> <p>играем</p> <a ref="тема">по нареждане</a>.</example>
        </sense>
        
        <!-- Значение 8 -->
        <sense>
            <def src="D"><a ref="агенс">някой</a> манипулира <a ref="тема">чувствата или възприятията на друг</a></def>
            <frame>
                <arg semantic_role="агенс" function="подлог">
                    <syntactic_structure><NP/><pro/></syntactic_structure>
                    <selective_restrictions><sel_restr>човек</sel_restr></selective_restrictions>
                </arg>
            </frame>
            <example src="D"><a ref="агенс">Той</a> <p>играе</p> <a ref="тема">с нея</a>.</example>
            <example src="D"><a ref="агенс">Тя</a> <p>играе</p> <a ref="тема">игра на доверие</a>.</example>
            <example src="D"><a ref="агенс">Момчето</a> <p>играе</p> <a ref="тема">ролята на добрия</a>.</example>
            <example src="D"><a ref="агенс">Те</a> <p>играят</p> <a ref="тема">психологическа игра</a>.</example>
            <example src="D"><a ref="агенс">Той</a> <p>играе</p> <a ref="тема">с чужди усещания</a>.</example>
